sudo: false
language: node_js
node_js:
- '5.11'
branches:
  only:
  - develop
script:
- ./deploy.sh
env:
  global:
    secure: pVA7OWkX/ewPvm0ekiJaNigQypE5lO4d3hBJ0+IjtwFhV+KZz54H/xroMUcI/NARidLYzQ1S7c3ODI0hF8KH2Oj8G1fqw9tAhaz+YPGqfb8gyZCfUpkSY2hydbXvkoMKzMsY5NV8g4asxxw/5tlTKHvnzAGkee2Gj1wZKdJByoyEBhflK8MtQHajkq+T7bGawsZ8ldRk1VksjxKwOdhEVjMZ0X7RrZPMgch3qfRGWzSSmSyejyhvC2ambMFM8FqMMfP48wUsm9ty+YfRgIU3aLgvx8KY+vFXO4PHFd5C//HYBCRjJ1WNrMW+9Kl7N48JhgUfzJ/faDfbBmkBV1K0fkhuQLeP+h5Uconpc+Xc/RMwAH5ZdHZKNwVpW3I1lNoebMz/e4+HAvfQnSc1LipmCDWK/RMUeYN+2+pdX84gql6yiYBctT7/ZH/xfHExKznn4UfEoyGQv/Afan1NMkd7h/Y8a4ZBY0he4fzOCOAjeNRLg3CJi76f1A885FJRKXqG+eHhBrAQRArwuPiJtw/xqS35e4Pvtui8AFB0ARfz7IJOzLGChLs5aFv6YE4CdJBYeeBAkmn4pp0g7WaB93IA6xiASmJXOhqQMmOXiXGtLQuvjRHTsFgLHA4TpKPUXAjjAfayUX6MC2emDsq5tToOZW27EELTul1E88xBfeokKh0=
